### ISSUE TITLE
Request for AP Pschology Notes

### ISSUE THREAD

**Issue by Y0ngg** [Jay-Feng2008/SUIShare#2]
Requesting for AP Psychology Notes

**Comment by SUISWY-Academic-Department** [comment]
We have added a directory for [AP Psychology](https://github.com/SUISWY-Academic-Department/SUIShare/tree/master/Social%20Science/AP%20Psychology) under department [Social Science](https://github.com/SUISWY-Academic-Department/SUIShare/tree/master/Social%20Science), currently including [**past exam papers**](https://github.com/SUISWY-Academic-Department/SUIShare/tree/master/Social%20Science/AP%20Psychology/Past%20Papers), [**links to study materials**](https://github.com/SUISWY-Academic-Department/SUIShare/tree/master/Social%20Science/AP%20Psychology/Links), [**textbooks**](https://github.com/SUISWY-Academic-Department/SUIShare/tree/master/Social%20Science/AP%20Psychology/Textbooks), and a cheatsheet for [**notes**](https://github.com/SUISWY-Academic-Department/SUIShare/tree/master/Social%20Science/AP%20Psychology/Notes).      
We are still collecting more notes from past students of this course (e.g., hand-written notebooks). Updates will be informed here once we are able to obtain more resources.

**Comment by Y0ngg** [comment]
Thank you for your service!
